### ISSUE TITLE
Not able to load the model from provided .pt file

### ISSUE THREAD

**Issue by jeevan-exa** [AI4Bharat/pratilipi#1]
I have followed the steps and set up the environment on Ubuntu 18.04. But while running it facing the following issue.
```python flask_api.py cpu
/home/jeeva/.local/lib/python3.7/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

Killed```

I believe it is an issue with memory limitation but not sure. Can you please help us with this issue and also specify the hardware requirements for CPU only and with GPU?

**Comment by jeevan-exa** [comment]
I have backtracked the code and found that in support.py, the 'load_model' function has a while loop that is not ending and consuming the whole memory. 

```
def load_model(mdl_path):
    while True:
        try:
            mdl, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([mdl_path])
            print("Successfully loaded model "+mdl_path)
            break

        except:
            m = torch.load(mdl_path)
            m['cfg']['task']['_name'] = 'audio_finetuning'
            torch.save(m,mdl_path)
    return mdl[0].eval(), task.target_dictionary
```

if I remove the while loop and have only one try and except block like below,
```
def load_model(mdl_path):
    print("Loading model....")
    # while True:
    try:
        mdl, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([mdl_path])
        print("Successfully loaded model "+mdl_path)
        #break
    except:
        m = torch.load(mdl_path)
        m['cfg']['task']['_name'] = 'audio_finetuning'
        torch.save(m,mdl_path)
        mdl, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([mdl_path])
        print("Successfully loaded model "+mdl_path)
    return mdl[0].eval(), task.target_dictionary
```

then I am getting the following error
```
Loading model....
tcmalloc: large alloc 1262125056 bytes == 0x55a21f34c000 @  0x7f6d74ea0b6b 0x7f6d74ec0379 0x7f6c65a04cde 0x7f6c65a06452 0x7f6cb8bec571 0x7f6d614130b6 0x7f6d60b84aa8 0x55a1cbe35098 0x55a1cbea84d9 0x55a1cbea2ced 0x55a1cbe35bda 0x55a1cbea3915 0x55a1cbea2ced 0x55a1cbe357f3 0x55a1cbe352f9 0x55a1cbf7c35d 0x55a1cbeeba0b 0x55a1cbe343a1 0x55a1cbf25e1d 0x55a1cbea7e99 0x55a1cbea2ced 0x55a1cbd74e2b 0x55a1cbea4fe4 0x55a1cbea29ee 0x55a1cbe35bda 0x55a1cbea4737 0x55a1cbea29ee 0x55a1cbe35bda 0x55a1cbea3915 0x55a1cbea29ee 0x55a1cbe35bda
tcmalloc: large alloc 1262125056 bytes == 0x55a26a6f4000 @  0x7f6d74ea0b6b 0x7f6d74ec0379 0x7f6c65a04cde 0x7f6c65a06452 0x7f6cb8bec571 0x7f6d614130b6 0x7f6d60b84aa8 0x55a1cbe35098 0x55a1cbea84d9 0x55a1cbea2ced 0x55a1cbe35bda 0x55a1cbea3915 0x55a1cbea2ced 0x55a1cbe357f3 0x55a1cbe352f9 0x55a1cbf7c35d 0x55a1cbeeba0b 0x55a1cbe343a1 0x55a1cbf25e1d 0x55a1cbea7e99 0x55a1cbea2ced 0x55a1cbd74e2b 0x55a1cbea4fe4 0x55a1cbea29ee 0x55a1cbe35bda 0x55a1cbea4737 0x55a1cbea29ee 0x55a1cbe35bda 0x55a1cbea3915 0x55a1cbea29ee 0x55a1cbe35bda
Traceback (most recent call last):
  File "flask_api.py", line 37, in <module>
    model,dictionary = load_model(m['model_path'])
  File "/content/pratilipi/speech-api/app/support.py", line 246, in load_model
    mdl, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([mdl_path])
  File "/content/pratilipi/speech-api/app/fairseq/checkpoint_utils.py", line 470, in load_model_ensemble_and_task
    model = task.build_model(cfg.model, from_checkpoint=True)
  File "/content/pratilipi/speech-api/app/fairseq/tasks/audio_finetuning.py", line 193, in build_model
    model = super().build_model(model_cfg, from_checkpoint)
  File "/content/pratilipi/speech-api/app/fairseq/tasks/audio_pretraining.py", line 197, in build_model
    model = super().build_model(model_cfg, from_checkpoint)
  File "/content/pratilipi/speech-api/app/fairseq/tasks/fairseq_task.py", line 335, in build_model
    model = models.build_model(cfg, self, from_checkpoint)
  File "/content/pratilipi/speech-api/app/fairseq/models/__init__.py", line 106, in build_model
    return model.build_model(cfg, task)
  File "/content/pratilipi/speech-api/app/fairseq/models/wav2vec/wav2vec2_asr.py", line 212, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, len(task.target_dictionary))
  File "/content/pratilipi/speech-api/app/fairseq/models/wav2vec/wav2vec2_asr.py", line 410, in __init__
    task = tasks.setup_task(w2v_args.task)
  File "/content/pratilipi/speech-api/app/fairseq/tasks/__init__.py", line 39, in setup_task
    cfg = merge_with_parent(dc(), cfg)
  File "/content/pratilipi/speech-api/app/fairseq/dataclass/utils.py", line 490, in merge_with_parent
    merged_cfg = OmegaConf.merge(dc, cfg)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/omegaconf.py", line 321, in merge
    target.merge_with(*others[1:])
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py", line 331, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py", line 329, in merge_with
    self._merge_with(*others)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py", line 347, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py", line 314, in _map_merge
    dest[key] = src._get_node(key)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py", line 259, in __setitem__
    key=key, value=value, type_override=ConfigKeyError, cause=e
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigKeyError: Key 'eval_wer' not in 'AudioPretrainingConfig'
	full_key: eval_wer
	reference_type=Optional[AudioPretrainingConfig]
	object_type=AudioPretrainingConfig
```

Any help on this setup is much appreciated. Thanks!

**Comment by tahirjmakhdoomi** [comment]
Hi. Thanks for pointing out. 

Can you go to this file and paste the function here?

```
File "/content/pratilipi/speech-api/app/fairseq/dataclass/utils.py", line 490, in merge_with_parent
    merged_cfg = OmegaConf.merge(dc, cfg)
```

There is one argument in the function "merge_with_parent" named as remove_missing. Set it to True and try again with your process.
